[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "thor"
version = "0.1.0"

[project.scripts]
thor = "src.main:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["src"]
